version: "3.8"
services:
  trojan-client:
    env_file: ./.env
    container_name: sing-box-trojan-client
    image: sing-box-${OS}-${ARCH}:${SING_BOX_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        ARCH: ${ARCH}
        SING_BOX_VERSION: ${SING_BOX_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      network: host
    network_mode: host
    volumes:
      - ${TROJAN_CLIENT_CONFIG}:/sing-box-${SING_BOX_VERSION}-${OS}-${ARCH}/${TROJAN_CLIENT_CONFIG}:ro
    command: "./sing-box -c ${TROJAN_CLIENT_CONFIG} run"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  trojan-server:
    env_file: ./.env
    container_name: sing-box-trojan-server
    image: sing-box-${OS}-${ARCH}:${SING_BOX_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        ARCH: ${ARCH}
        SING_BOX_VERSION: ${SING_BOX_VERSION}
      network: host
    network_mode: host
    volumes:
      - ${TROJAN_SERVER_CONFIG}:/sing-box-${SING_BOX_VERSION}-${OS}-${ARCH}/${TROJAN_SERVER_CONFIG}:ro
      - ${SSL_CERT}:${SSL_CERT}:ro
      - ${SSL_CERT_KEY}:${SSL_CERT_KEY}:ro
    command: "./sing-box -c ${TROJAN_SERVER_CONFIG} run"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
