version: "3.8"
services:
  client:
    env_file: ./.env
    container_name: sing-box-client
    image: sing-box-${OS}-${ARCH}:${SING_BOX_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        ARCH: ${ARCH}
        SING_BOX_VERSION: ${SING_BOX_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      network: host
    network_mode: host
    volumes:
      - ${CLIENT_CONFIG}:/sing-box-${SING_BOX_VERSION}-${OS}-${ARCH}/${CLIENT_CONFIG}:ro
    command: "./sing-box -c ${CLIENT_CONFIG} run"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  server:
    env_file: ./.env
    container_name: sing-box-server
    image: sing-box-${OS}-${ARCH}:${SING_BOX_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        ARCH: ${ARCH}
        SING_BOX_VERSION: ${SING_BOX_VERSION}
      network: host
    network_mode: host
    volumes:
      - ${SERVER_CONFIG}:/sing-box-${SING_BOX_VERSION}-${OS}-${ARCH}/${SERVER_CONFIG}:ro
      - ${SSL_CERT}:${SSL_CERT}:ro
      - ${SSL_CERT_KEY}:${SSL_CERT_KEY}:ro
    command: "./sing-box -c ${SERVER_CONFIG} run"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
